/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as OdooSplatRouteImport } from './routes/odoo.$'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ApiOdooSplatRouteImport } from './routes/api/odoo.$'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OdooSplatRoute = OdooSplatRouteImport.update({
  id: '/odoo/$',
  path: '/odoo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOdooSplatRoute = ApiOdooSplatRouteImport.update({
  id: '/api/odoo/$',
  path: '/api/odoo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/portal': typeof PortalRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/odoo/$': typeof OdooSplatRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/odoo/$': typeof ApiOdooSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/portal': typeof PortalRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/odoo/$': typeof OdooSplatRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/odoo/$': typeof ApiOdooSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/portal': typeof PortalRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/odoo/$': typeof OdooSplatRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/odoo/$': typeof ApiOdooSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/lookbook'
    | '/portal'
    | '/wishlist'
    | '/collections/$slug'
    | '/odoo/$'
    | '/shop/$slug'
    | '/collections/'
    | '/shop/'
    | '/api/odoo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/lookbook'
    | '/portal'
    | '/wishlist'
    | '/collections/$slug'
    | '/odoo/$'
    | '/shop/$slug'
    | '/collections'
    | '/shop'
    | '/api/odoo/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/lookbook'
    | '/portal'
    | '/wishlist'
    | '/collections/$slug'
    | '/odoo/$'
    | '/shop/$slug'
    | '/collections/'
    | '/shop/'
    | '/api/odoo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  LookbookRoute: typeof LookbookRoute
  PortalRoute: typeof PortalRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  OdooSplatRoute: typeof OdooSplatRoute
  ShopSlugRoute: typeof ShopSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiOdooSplatRoute: typeof ApiOdooSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odoo/$': {
      id: '/odoo/$'
      path: '/odoo/$'
      fullPath: '/odoo/$'
      preLoaderRoute: typeof OdooSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/odoo/$': {
      id: '/api/odoo/$'
      path: '/api/odoo/$'
      fullPath: '/api/odoo/$'
      preLoaderRoute: typeof ApiOdooSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  LookbookRoute: LookbookRoute,
  PortalRoute: PortalRoute,
  WishlistRoute: WishlistRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  OdooSplatRoute: OdooSplatRoute,
  ShopSlugRoute: ShopSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiOdooSplatRoute: ApiOdooSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
